version: '3'
name: nft-marketplace
services:
  db:
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    networks:
      - app-net
networks:
  app-net:
