services:
  marketplace:
    ports:
      - 3000:3000
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
    restart: always
    networks:
      - app-net

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    ports:
      # - 80:80
      # - 443:443
      - 8080:80
    depends_on:
      - marketplace
    restart: always
    environment:
      - NGINX_PORT=80
    networks:
      - app-net
