services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker-host.sock
      - ./:/workspace:cached
      - ./.pnpm-store:/workspace/.pnpm-store
      - ./node_modules:/workspace/node_modules
    user: node
    networks:
      - app-net
